### 1. Student Marks Analyzer
You are helping a teacher check exam results.
 Create a NumPy array with 10 random integers between 0 and 100 (student scores).

 Find:
 - the highest score
 - the lowest score
 - the average score

In [9]:
import numpy as np

arr = np.random.randint(0,101, (10))
print(arr)

print(np.max(arr))
print(arr.min())
print(arr.mean())

[59 48 11 59 75  6 77 89 47 30]
89
6
50.1


### 2. Warehouse Weights
A warehouse stores item weights (in kg):
 arr = np.array([45, 60, 55, 30, 90, 75, 40, 50])

 Find and print:
 - all items heavier than 50 kg
 - the sorted weights
 - the index of the heaviest item


In [16]:
arr = np.array([45, 60, 55, 30, 90, 75, 40, 50])

print(arr[arr > 50])
arr.sort()
print(arr[::-1])
print(arr)
print(np.argmax(arr))

[60 55 90 75]
[90 75 60 55 50 45 40 30]
[30 40 45 50 55 60 75 90]
7


### 3. Temperature Report
A weather station collects temperatures (°C) from 4 zones.
 Generate random integers between 20 and 40 for a 4×4 grid.

 Then find:
 - the average temperature of each zone (row)
 - the highest temperature in the grid
 - replace all temperatures above 35 with 35

In [18]:
arr = np.random.randint(20,40, (4,4))
print(arr)

# for r in arr:
#     print(r.mean())

print(arr.mean(axis=1))
print(np.max(arr))
arr[arr > 35] = 35
print(arr)

[[31 21 31 29]
 [36 37 33 30]
 [29 28 34 30]
 [29 22 35 36]]
[28.   34.   30.25 30.5 ]
37
[[31 21 31 29]
 [35 35 33 30]
 [29 28 34 30]
 [29 22 35 35]]


### 4. Traffic Data
A city records the number of cars passing 5 intersections in 3 time slots (morning, afternoon, night).
 Create a 3×5 array of random integers between 0 and 50.

 Then find:
 - total cars per intersection (sum by column)
 - total cars per time slot (sum by row)

In [22]:
arr = np.random.randint(0,51, (3,5))
print(arr)
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

[[22 44 32 17  0]
 [41 13 23 49 17]
 [29 43 12  9 42]]
[ 92 100  67  75  59]
[115 143 135]


### 5. Fruit Store Stock
You sell fruits in your store. Stock levels (kg) for 5 days are:
 stock = np.array([12, 15, 9, 20, 18])

 A new delivery adds 5 kg to each stock.
 Then 10% of all fruits get spoiled.

 Find the final stock levels.

In [27]:
arr = np.array([12, 15, 9, 20, 18], dtype=float)
arr += 5
print(arr)
arr -= 0.1 * arr
print(arr)

[17. 20. 14. 25. 23.]
[15.3 18.  12.6 22.5 20.7]
