#### 1 . Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.

In [15]:
import numpy as np

arr_1d = np.random.randint(1,10,size=(3))
arr_2d = np.random.randint(1,10,size=(3,3))
arr_3d = np.random.randint(1,10,size=(3,3,3))

# print(arr_1d, end="\n\n")
# print(arr_2d, end="\n\n")
# print(arr_3d, end="\n\n")

print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

print(arr_1d.shape)
print(arr_2d.shape)
print(arr_3d.shape)

print(arr_1d.dtype)
print(arr_2d.dtype)
print(arr_3d.dtype)

print(arr_1d.size)
print(arr_2d.size)
print(arr_3d.size)

1
2
3
(3,)
(3, 3)
(3, 3, 3)
int32
int32
int32
3
9
27


#### 2 . Create:
 * an array of zeros of shape (3,3)
 * an array of ones of shape (2,5)
 * an array filled with 7


In [28]:
array_of_zeros = np.zeros((3,3))
print(array_of_zeros)

array_of_ones = np.ones((2,5))
print(array_of_ones)

# array_with_7 = np.random.randint(7,8,(3,3))
array_with_7 = np.full((3,3),7)
print(array_with_7)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


#### 3 . Create an array of even numbers between 10 and 50 using arange.

In [40]:
arr_even = np.arange(10,51,2)
# arr_even = np.linspace(10,50,21,dtype=int)
print(arr_even)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### 4 . Create a 4×4 matrix from 0–15. Then , extract:
* the first row
* the last column
* a 2×2 subarray from the center


In [ ]:
arr = np.random.randint(0,16,(4,4))
row_one = arr[0:1,:]
last_column = arr[:,3:]

print(arr,end="\n\n")
print(row_one, end="\n\n")
print(last_column)


[[14  0 15 15]
 [ 8  0  8 10]
 [15 12  6 10]
 [ 2  5 13  9]]

[[14  0 15 15]]

[[15]
 [10]
 [10]
 [ 9]]


5 . Add a 1D array [1,2,3] to each row of a 3×3 matrix.

In [53]:
arr1 = np.random.randint(1,10,(3,3))
arr2 = np.array([1,2,3])

print(arr1,end="\n\n")

ans = arr1 + arr2
print(ans)

[[6 9 8]
 [8 5 9]
 [3 7 5]]

[[ 7 11 11]
 [ 9  7 12]
 [ 4  9  8]]


#### 6 . Given two arrays A and B, compute:
* (A + B) / 2
* A^2 + B^2


In [64]:
arr_a = np.random.randint(1,10,(2,2))
arr_b = np.random.randint(1,10,(2,2))

print(arr_a, end="\n\n")
print(arr_b, end="\n\n")

ans1 = (arr_a + arr_b) / 2
ans2 = arr_a ** 2 + arr_b ** 2

print(ans1, end="\n\n")
print(ans2, end="\n\n")

[[9 4]
 [1 7]]

[[2 5]
 [5 2]]

[[5.5 4.5]
 [3.  4.5]]

[[85 41]
 [26 53]]

